In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X=iris['data']

In [4]:
y=iris['target']

In [5]:
knn = KNeighborsClassifier(n_neighbors=3)

In [6]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [10]:
y_pred=knn.predict([[5.1,3.5,1.4,0.2],[5.5,2.3,4.,1.3],[6.7,3.3,5.7,2.5]])

In [11]:
y_pred

array([0, 1, 2])

In [9]:
# Don't use full data for model training as we are not able to test result is acurate or not
# So divide data into parts - few data for training and few data for testing
# After training we can test model using Test data

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3,random_state=6,stratify=y)

In [16]:
# Train your model with Train data

In [17]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [18]:
y_pred=knn.predict([[5.1,3.5,1.4,0.2],[5.5,2.3,4.,1.3],[6.7,3.3,5.7,2.5]])

In [19]:
y_pred

array([0, 1, 2])

In [20]:
#Actaul result 
y_test

array([2, 2, 2, 0, 1, 1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 2, 2, 0, 2, 0, 2, 1,
       0, 0, 0, 2, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1,
       2])

In [22]:
# Model predict result
y_pred=knn.predict(X_test)
y_pred

array([2, 2, 1, 0, 1, 1, 2, 0, 1, 1, 2, 0, 2, 0, 1, 2, 2, 0, 2, 0, 2, 1,
       0, 0, 0, 2, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1,
       2])

In [23]:
# few results are not matching with actaul result - by manually verifying 
# How to check model acuracy with function? Using accuracy_score function

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
accuracy_score(y_test,y_pred)

0.9333333333333333

In [26]:
# How to get good accuarcy percentage ?? by changing model parameteres
# Hyper parameter tuning with GridSearchCV

In [27]:
from sklearn.model_selection import GridSearchCV


GridSearchCV(
    ['estimator', 'param_grid', 'scoring=None', 'fit_params=None', 'n_jobs=None', "iid='warn'", 'refit=True', "cv='warn'", 'verbose=0', "pre_dispatch='2*n_jobs'", "error_score='raise-deprecating'", "return_train_score='warn'"],
)


In [42]:
import numpy as np
param_grid = {'n_neighbors':np.arange(1, 50),'weights':['uniform','distance']}

knn_cv= GridSearchCV(knn,param_grid,cv=5)

In [43]:
knn_cv.fit(X, y)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]), 'weights': ['uniform', 'distance']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [44]:
knn_cv.best_params_

{'n_neighbors': 10, 'weights': 'distance'}

In [45]:
knn_cv.best_score_

0.9866666666666667

In [61]:
knn_accurate = KNeighborsClassifier(n_neighbors=10,weights='distance')

In [62]:
knn_accurate.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=10, p=2,
           weights='distance')

In [63]:
y_accurate_pred = knn_accurate.predict(X_test)
y_accurate_pred

array([2, 2, 1, 0, 1, 1, 2, 0, 1, 1, 2, 0, 2, 0, 1, 2, 2, 0, 2, 0, 2, 1,
       0, 0, 0, 2, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1,
       2])

In [64]:
y_test

array([2, 2, 2, 0, 1, 1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 2, 2, 0, 2, 0, 2, 1,
       0, 0, 0, 2, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1,
       2])

In [65]:
y_pred

array([2, 2, 1, 0, 1, 1, 2, 0, 1, 1, 2, 0, 2, 0, 1, 2, 2, 0, 2, 0, 2, 1,
       0, 0, 0, 2, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1,
       2])

In [66]:
accuracy_score(y_test,y_accurate_pred)

0.9333333333333333

In [67]:
# Another Accuracy function RandomizedSearchCV

RandomizedSearchCV(
    ['estimator', 'param_distributions', 'n_iter=10', 'scoring=None', 'fit_params=None', 'n_jobs=None', "iid='warn'", 'refit=True', "cv='warn'", 'verbose=0', "pre_dispatch='2*n_jobs'", 'random_state=None', "error_score='raise-deprecating'", "return_train_score='warn'"],
)

In [68]:
from sklearn.model_selection import RandomizedSearchCV

In [72]:
param_grid = {'n_neighbors':np.arange(1, 50),'weights':['uniform','distance']}

knn_rcv= RandomizedSearchCV(knn,param_grid,cv=5)

In [73]:
knn_rcv.fit(X,y)

RandomizedSearchCV(cv=5, error_score='raise-deprecating',
          estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform'),
          fit_params=None, iid='warn', n_iter=10, n_jobs=None,
          param_distributions={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]), 'weights': ['uniform', 'distance']},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0)

In [74]:
knn_rcv.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=11, p=2,
           weights='distance')

In [75]:
knn_rcv.best_params_

{'weights': 'distance', 'n_neighbors': 11}

In [76]:
knn_rcv.best_score_

0.9866666666666667

In [77]:
knn_accurate_2 = KNeighborsClassifier(n_neighbors=11,weights='distance')

In [78]:
knn_accurate_2.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=11, p=2,
           weights='distance')

In [79]:
y = knn_accurate_2.predict(X_test)
y

array([2, 2, 1, 0, 1, 1, 2, 0, 1, 1, 2, 0, 2, 0, 1, 2, 2, 0, 2, 0, 2, 1,
       0, 0, 0, 2, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1,
       2])

In [80]:
y_test

array([2, 2, 2, 0, 1, 1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 2, 2, 0, 2, 0, 2, 1,
       0, 0, 0, 2, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1,
       2])